### PR TITLE
Add bower.json

### PR DESCRIPTION
**Pull request by jvandyke**
Enables better registry in the Bower index. After committing, the code should be tagged as the same version as is in this file.

Closes https://github.com/fronteed/iCheck/issues/34 and https://github.com/fronteed/iCheck/issues/76

### CODE REVIEW

**Comment by drgullin** [comment]
Thanks @jvandyke, I've fixed some issues in bower.json and added it to the repo.

**Comment by jvandyke** [comment]
You're the man. Thanks!

**Comment by kulte** [comment]
This doesn't seem to install anything besides for the README...

**Comment by drgullin** [comment]
It's not updated yet in the bower packages list https://github.com/bower/bower/issues/120#issuecomment-30930239

**Pull request closed without merging**
