### PR TITLE
Add ARIA accessibility

### PR DESCRIPTION
**Pull request by valpackett**
Tested with VoiceOver on OS X and iOS. :+1:

### CODE REVIEW

**Comment by drgullin** [comment]
Well done :+1: 

I think this should be an option.
Can you please update the code?
It should add ARIA attributes when `aria` option is ON (should be OFF by default).

**Comment by valpackett** [comment]
Why do you think so?
There's no reason anyone would want to disable this.
ARIA never causes any problems.
The option would just add more bytes for no good reason.

**Comment by drgullin** [comment]
It should be an option because of the performance reasons. 

When iCheck is used on the admin pages and there're many checkboxes, `aria` option may slow down the overall performance. Since admin pages are closed for regular users, ARIA support may not be needed.

**Comment by skarkkai** [comment]
I would encourage you to enable ARIA support by default. People typically don't change default config unless necessary, due to time constraints and laziness. Finland's biggest newspaper just started using iCheck for their online polls, and they obviously haven't enabled ARIA support because the polls are completely unusable with a screen reader.

**Pull request merged**
