### PR TITLE
Added option to fire change event to be compatible with default behavior

### PR DESCRIPTION
**Pull request by nathanjosiah**
This allows the default change event to be fired at the appropriate times. As it stands now, the plugin breaks default behavior and makes it very difficult to integrate into applications. For example, the `ifChanged` event fires multiple times both before and after the actual change has happened with no way to differentiate between the two and the `ifClicked` event doesn't fire when keyboard shortcuts are used. Even if these events are to be used they require everyone in a codebase to know them and can remember to use the propriatary methods and event names. This PR makes all of this a non-issue by enabling default behavior with events and event naming. 
Since you didn't have a contributors file, I wasn't sure what to do about versioning as well as your prefered minifier so I ran it through Closure Compiler and left the version numbers all the same (1.0.2)

This PR would address https://github.com/fronteed/icheck/issues/244

Let me know of any feedback including if you would like me to include examples, update `README` with new options, or change version numbers.

### CODE REVIEW

**Comment by nathanjosiah** [comment]
This PR would address https://github.com/fronteed/icheck/issues/244

**Comment by nathanjosiah** [comment]
I have updated version numbers and added documentation to the new option. Probably worth mentioning, the new option from this PR is `false` by default to maintain the current behavior by default for backwards compatibility.

**Comment by nathanjosiah** [comment]
I have added another commit that allows the element to be manipulated without using iCheck and triggering the `change` event will update the state of the plugin elements.

**Comment by nathanjosiah** [comment]
Here is [an demo](https://jsfiddle.net/nathanjosiah/wykncjj4/) of all of the changed from this PR.

**Comment by drgullin** [comment]
This can be easily done by changing nearly a list line in code:

```js
input[_callback]('ifChanged')[_callback]('if' + capitalize(callback))[_callback]('change');
```

**Comment by drgullin** [comment]
@nathanjosiah thanks, this is supported now by default in v1.0.3.

**Pull request closed without merging**
