### PR TITLE
Fix selector error

### PR DESCRIPTION
**Pull request by olragon**
When input name is in array format, iCheck trigger jQuery error, this pull request fix that by escape selector name before process.

HTML

```
<input type="checkbox" name="check[me]">
```

Javascript

```
$('input').iCheck();
```

### CODE REVIEW

**Comment by drgullin** [comment]
Thanks.

Try to fix this issue by replacing `$('input[name=' + safeName + ']').each(function() {` with `$('input[name="' + input[0].name + '"]')`. Additional quotes should help.

**Comment by olragon** [comment]
You right!

**Comment by drgullin** [comment]
Use Google Closure for minification, please. Then I will merge this pull request.
http://closure-compiler.appspot.com/home

**Comment by olragon** [comment]
Done!

**Pull request merged**
